### ISSUE TITLE
🐛 [Bug]Crash logs of some servers after using eluna scripts

### ISSUE THREAD

**Issue by leechunlung** [Eluna-Ports/Eluna-VMaNGOS#3]
## Crash! 2024/2/27 13:36:49. mangosd.exe has crashed! Lines logged from logs\Server.log

[0x3f0cc]
[0x37481]
[0x365f1]
[0x22f04]
[0x1c2ce]
configthreadlocale()+0x92 [0x21bb2]
BaseThreadInitThunk()+0x14 [0x17344]
RtlUserThreadStart()+0x21 [0x526b1]

2024-02-27 13:36:45 CATCH Exception 'ASSERT' for account 4
2024-02-27 13:36:45 number_of_arguments == this->push_counter
2024-02-27 13:36:48 D:\a\Eluna-VMaNGOS\Eluna-VMaNGOS\src\modules\Eluna\HookHelpers.h:21: Error: Assertion in Eluna::SetupStack failed: number_of_arguments == this->push_counter
2024-02-27 13:36:48 [0x24f997]
[0x24f855]
[0x1e9150]
[0x1ea224]
[0x1e9e03]
[0x1e973b]
ACE_TP_Reactor::handle_socket_events()+0x119 [0x9ae99]
ACE_TP_Reactor::dispatch_i()+0xde [0x9abae]
ACE_TP_Reactor::handle_events()+0x1fc [0x9aa5c]
ACE_Reactor::run_reactor_event_loop()+0x3d [0x7db9d]
[0x9c2fa]
ACE_Task_Base::svc_run()+0x41 [0x9be81]
ACE_Thread_Adapter::invoke_i()+0x69 [0x9c429]
ACE_Thread_Adapter::invoke()+0xcd [0x9c38d]
configthreadlocale()+0x92 [0x21bb2]
BaseThreadInitThunk()+0x14 [0x17344]
RtlUserThreadStart()+0x21 [0x526b1]

**Comment by Niam5** [comment]
Please provide scripts used and conditions that cause the crash. Unfortunately your crash log is no help.

**Comment by leechunlung** [comment]
https://mega.nz/file/4u0FjCga#A163uQtWagg0_DC0_HrtkrnpGLS3kET9oVu2wDMgt3A
A announce lua script. 
besides, no whispers between characters

**Comment by Niam5** [comment]
I get no crash with the provided script. Not the best way to do timed event since it's fireing the hook on every single packet and doing that could add some nasty overhead at scale but that design decision is up to you.

**Comment by leechunlung** [comment]
It seems that many scripts can cause crashes, this did not occur in previous builds.by the way, characters cannot whisper

**Comment by Niam5** [comment]
Previous builds, prior to the multistate update were using an older version of Eluna. I expected some issues with the multistate update since the update did change alot of things and the code base is different enough from TC/CMaNGOS that the placement of functions has been a bit different leading to these bugs. If any scripts cause a crash I need to see the script and know the conditions that trigger the crash to be able to debug it.

**Comment by leechunlung** [comment]
Indeed, the code base of VMangos and CMangos are different, and I believe this is a complex matter.there are too many types of scripts, I cannot provide all of them.But there are the same logs in all the errors about eluna engine,ex:
2024-02-28 01:39:07 ERROR: [Eluna]: Cannot execute call: registered value is (null), not a function.
2024-02-28 01:39:07 D:\a\Eluna-VMaNGOS\Eluna-VMaNGOS\src\modules\Eluna\LuaEngine.cpp:375: Error: Assertion in Eluna::ExecuteCall failed: false

2024-02-28 01:48:20 number_of_arguments == this->push_counter
2024-02-28 01:48:21 D:\a\Eluna-VMaNGOS\Eluna-VMaNGOS\src\modules\Eluna\HookHelpers.h:21: Error: Assertion in Eluna::SetupStack failed: number_of_arguments == this->push_counter

2024-02-28 02:48:51 ERROR: WorldPacket missing metatable
2024-02-28 02:48:51 D:\a\Eluna-VMaNGOS\Eluna-VMaNGOS\src\modules\Eluna\HookHelpers.h:32: Error: Assertion in Eluna::SetupStack failed: arguments_top >= number_of_arguments

2024-02-28 02:51:42 ERROR: lua_scripts/Server_yell.lua:6: bad argument #1 to 'time' (table expected, got userdata)

2024-02-28 07:36:13 ERROR: [Eluna]: Cannot execute call: registered value is table: 000001BB1734D3F0, not a function.
2024-02-28 07:36:13 D:\a\Eluna-VMaNGOS\Eluna-VMaNGOS\src\modules\Eluna\LuaEngine.cpp:375: Error: Assertion in Eluna::ExecuteCall failed: false

2024-02-28 09:42:07 ERROR: lua_scripts/extensions/ObjectVariables.ext:43: attempt to call method 'GetGUIDLow' (a nil value)

2024-02-28 10:21:18 ERROR: lua_scripts/extensions/ObjectVariables.ext:42: attempt to index local 'obj' (a userdata value)
![1](https://github.com/Niam5/Eluna-VMaNGOS/assets/143220143/b3f748c6-1462-487f-8216-e0ede2d324da)

I don't know if it's helpful for you, but every crash and eluna related error is here. Yesterday, the server crashed a total of 85 times.The problem is quite serious and may require a lot of modifications.

**Comment by leechunlung** [comment]
2024-02-28 11:30:50 D:\a\Eluna-VMaNGOS\Eluna-VMaNGOS\src\modules\Eluna\ElunaTemplate.h:45: Error: Assertion in ElunaGlobal::thunk failed: false
At this moment, a new error occurred. I don't have many scripts, and they are all very simple scripts.
Anyway, thank you for building it whether it's usable or not

**Comment by Niam5** [comment]
You are more then welcome to assist in the debugging process. You will need to build from source and in debug mode and have a debugger attached. Using the auto development builds won't do any good since they are built in release mode and have no debug symbols and are missing a lot of other stuff needed to assist with debugging. Just to be clear I will NOT be rolling back the multistate changes. If you wish to do so you can since the multistate commit is sperate from the initial Eluna commit in git, you will need to find the prechange Eluna however as just downloading the current Eluna repo will have the multistate in it.

The whisper issue should be fixed. I would also suggest if you are having crashes with multiple players on that you change  Eluna.CompatibilityMode to false. By default its true and if for some reason vmangos has multiple map updaters I have run into this issue before, By setting that to false it will enable the new multithreaded/per-map functions for Eluna and may help with your issue.

**Comment by Niam5** [comment]
After reviewing this was likely cause by multiple map threads running when Eluna was in compatibility mode. In this mode only 1 thread can be running or you will get crashes. I have added logic to force the thread count to 1 regardless of the config values if Eluna compatibility mode is on. This should fix a lot of the crashes you are seeing. If you set compatibility mode to false you will get the multi-threaded functions back and it shouldn't crash. Please try the new build and report back.

**Comment by leechunlung** [comment]
The problem still exists, but after removing server yell.lua script, the crash issue will be alleviated, otherwise startup will crash.
Is it related to RegisterServerEvent()  ?

**Comment by leechunlung** [comment]
local function shiqu (event, player, item, count)
RegisterPlayerEvent (32,shiqu)

local function AnnounceBossKilled (event, killer, killed)
RegisterPlayerEvent(7, AnnounceBossKilled)

When there are these two scripts, it seems like they will crash non-stop, but I'm not sure about it either

**Comment by Niam5** [comment]
You will need to provide more information such as COMPLETE scripts since the ones you put above are not even complete and are not valid lua. I have a feeling you are doing things inside the scripts and leaving it out here and since that seems to be the case I will not help further without the above mentioned COMPLETE script.
